version: '3.1'
services:
  db:
    image: 'mariadb:11.2'
    working_dir: /app
    volumes:
      - '.:/app'
      - './db:/var/lib/mysql'
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=jdevrpw
      - MARIADB_USER=jdev
      - MARIADB_PASSWORD=jdevpw
      - MARIADB_DATABASE=jdevdb
    ports:
      - '43001:3306'
  php:
    build: 
      context: ./php/
      dockerfile: Dockerfile-8.1
    working_dir: /var/www/html
    volumes:
      - './html:/var/www/html'
    ports:
      - '43000:80'